version: "3"

services:

  # Name of this "service"
  concat:

    # Reference: https://docs.docker.com/compose/compose-file/#image
    # The name of the image locally and/or from docker-hub
    image: labsyspharm/concat:latest

    # Reference: https://docs.docker.com/compose/compose-file/#short-syntax-3
    volumes:
     # Relative path to the host location containing the input data (Could also
     # be an absolute path). Is mounted inside the container at /mnt/input.
     # Mounted read-only for safety
     - ./data/:/mnt/input:ro
     # Absolute path to a location to put the output on the host (Could also be
     # an absolute path). Is mounted inside the container at /mnt/output
     - /tmp/:/mnt/output

    # Reference: https://docs.docker.com/compose/compose-file/#environment
    environment:
     # An example of an environment variable which is used by the containerized
     # application.
     - UPPERCASE=True
